---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 21/04/2019 21:20
---

---round
---@param num number
---@param numDecimalPlaces number
---@return number
---@public
function math.round(num, numDecimalPlaces)
    return tonumber(string.format("%." .. (numDecimalPlaces or 0) .. "f", num))
end

---starts
---@param String string
---@param Start number
---@return number
---@public
function string.starts(String, Start)
    return string.sub(String, 1, string.len(Start)) == Start
end

---@type table
ValUI.Menus = setmetatable({}, ValUI.Menus)

---@type table
---@return boolean
ValUI.Menus.__call = function()
    return true
end

---@type table
ValUI.Menus.__index = ValUI.Menus

---@type table
ValUI.CurrentMenu = nil

---@type table
ValUI.NextMenu = nil

---@type number
ValUI.Options = 0

---@type number
ValUI.ItemOffset = 0

---@type number
ValUI.StatisticPanelCount = 0

---@type table
ValUI.Settings = {
    Debug = false,
    Controls = {
        Up = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 172 },
                { 1, 172 },
                { 2, 172 },
                { 0, 241 },
                { 1, 241 },
                { 2, 241 },
            },
        },
        Down = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 173 },
                { 1, 173 },
                { 2, 173 },
                { 0, 242 },
                { 1, 242 },
                { 2, 242 },
            },
        },
        Left = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 174 },
                { 1, 174 },
                { 2, 174 },
            },
        },
        Right = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 175 },
                { 1, 175 },
                { 2, 175 },
            },
        },
        SliderLeft = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 174 },
                { 1, 174 },
                { 2, 174 },
            },
        },
        SliderRight = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 175 },
                { 1, 175 },
                { 2, 175 },
            },
        },
        Select = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 201 },
                { 1, 201 },
                { 2, 201 },
            },
        },
        Back = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 177 },
                { 1, 177 },
                { 2, 177 },
                { 0, 199 },
                { 1, 199 },
                { 2, 199 },
            },
        },
        Click = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 24 },
            },
        },
        Enabled = {
            Controller = {
                { 0, 2 }, -- Look Up and Down
                { 0, 1 }, -- Look Left and Right
                { 0, 25 }, -- Aim
                { 0, 24 }, -- Attack
            },
            Keyboard = {
                { 0, 201 }, -- Select
                { 0, 195 }, -- X axis
                { 0, 196 }, -- Y axis
                { 0, 187 }, -- Down
                { 0, 188 }, -- Up
                { 0, 189 }, -- Left
                { 0, 190 }, -- Right
                { 0, 202 }, -- Back
                { 0, 217 }, -- Select
                { 0, 242 }, -- Scroll down
                { 0, 241 }, -- Scroll up
                { 0, 239 }, -- Cursor X
                { 0, 240 }, -- Cursor Y
                { 0, 31 }, -- Move Up and Down
                { 0, 30 }, -- Move Left and Right
                { 0, 21 }, -- Sprint
                { 0, 22 }, -- Jump
                { 0, 23 }, -- Enter
                { 0, 75 }, -- Exit Vehicle
                { 0, 71 }, -- Accelerate Vehicle
                { 0, 72 }, -- Vehicle Brake
                { 0, 59 }, -- Move Vehicle Left and Right
                { 0, 89 }, -- Fly Yaw Left
                { 0, 9 }, -- Fly Left and Right
                { 0, 8 }, -- Fly Up and Down
                { 0, 90 }, -- Fly Yaw Right
                { 0, 76 }, -- Vehicle Handbrake
            },
        },
    },
    Audio = {
        Id = nil,
        Use = "ValUI",
        ValUI = {
            UpDown = {
                audioName = "HUD_FREEMODE_SOUNDSET",
                audioRef = "NAV_UP_DOWN",
            },
            LeftRight = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_LEFT_RIGHT",
            },
            Select = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "SELECT",
            },
            Back = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "BACK",
            },
            Error = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "ERROR",
            },
            Slider = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "CONTINUOUS_SLIDER",
                Id = nil
            },
        },
        NativeUI = {
            UpDown = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_UP_DOWN",
            },
            LeftRight = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_LEFT_RIGHT",
            },
            Select = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "SELECT",
            },
            Back = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "BACK",
            },
            Error = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "ERROR",
            },
            Slider = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "CONTINUOUS_SLIDER",
                Id = nil
            },
        }
    },
    Items = {
        Title = {
            Background = { Width = 431, Height = 90 },
            Text = { X = 215, Y = 20, Scale = 0.8 },
        },
        Subtitle = {
            Background = { Width = 431, Height = 37 },
            Text = { X = 8, Y = 3, Scale = 0.35 },
            PreText = { X = 425, Y = 3, Scale = 0.35 },
        },
        Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 0, Width = 431 },
        Navigation = {
            Rectangle = { Width = 431, Height = 18 },
            Offset = 5,
            Arrows = { Dictionary = "commonmenu", Texture = "shop_arrows_upanddown", X = 190, Y = -6, Width = 50, Height = 50 },
        },
        Description = {
            Bar = { Y = 4, Width = 431, Height = 4 },
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 30 },
            Text = { X = 8, Y = 10, Scale = 0.35 },
        },
    },
    Panels = {
        Grid = {
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 275 },
            Grid = { Dictionary = "pause_menu_pages_char_mom_dad", Texture = "nose_grid", X = 115.5, Y = 47.5, Width = 200, Height = 200 },
            Circle = { Dictionary = "mpinventory", Texture = "in_world_circle", X = 115.5, Y = 47.5, Width = 20, Height = 20 },
            Text = {
                Top = { X = 215.5, Y = 15, Scale = 0.35 },
                Bottom = { X = 215.5, Y = 250, Scale = 0.35 },
                Left = { X = 57.75, Y = 130, Scale = 0.35 },
                Right = { X = 373.25, Y = 130, Scale = 0.35 },
            },
        },
        Percentage = {
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 76 },
            Bar = { X = 9, Y = 50, Width = 413, Height = 10 },
            Text = {
                Left = { X = 25, Y = 15, Scale = 0.35 },
                Middle = { X = 215.5, Y = 15, Scale = 0.35 },
                Right = { X = 398, Y = 15, Scale = 0.35 },
            },
        },
    },
}

function ValUI.SetScaleformParams(scaleform, data)
    data = data or {}
    for k, v in pairs(data) do
        PushScaleformMovieFunction(scaleform, v.name)
        if v.param then
            for _, par in pairs(v.param) do
                if math.type(par) == "integer" then
                    PushScaleformMovieFunctionParameterInt(par)
                elseif type(par) == "boolean" then
                    PushScaleformMovieFunctionParameterBool(par)
                elseif math.type(par) == "float" then
                    PushScaleformMovieFunctionParameterFloat(par)
                elseif type(par) == "string" then
                    PushScaleformMovieFunctionParameterString(par)
                end
            end
        end
        if v.func then
            v.func()
        end
        PopScaleformMovieFunctionVoid()
    end
end

---Visible
---@param Menu function
---@param Value boolean
---@return table
---@public
function ValUI.Visible(Menu, Value)
    if Menu ~= nil then
        if Menu() then
            if type(Value) == "boolean" then
                if Value then
                    if ValUI.CurrentMenu ~= nil then
                        ValUI.CurrentMenu.Open = not Value
                    end
                    Menu:UpdateInstructionalButtons(Value);
                    ValUI.CurrentMenu = Menu
                    menuOpen = true
                else
                    menuOpen = false
                    ValUI.CurrentMenu = nil
                end
                Menu.Open = Value
                ValUI.Options = 0
                ValUI.ItemOffset = 0
                ValUI.LastControl = false
            else
                return Menu.Open
            end
        end
    end
end

function ValUI.CloseAll()
    menuOpen = false
    if ValUI.CurrentMenu ~= nil then
        local parent = ValUI.CurrentMenu.Parent
        while parent ~= nil do
            parent.Index = 1
            parent.Pagination.Minimum = 1
            parent.Pagination.Maximum = 10
            parent = parent.Parent
        end
        ValUI.CurrentMenu.Index = 1
        ValUI.CurrentMenu.Pagination.Minimum = 1
        ValUI.CurrentMenu.Pagination.Maximum = 10
        ValUI.CurrentMenu.Open = false
        ValUI.CurrentMenu = nil
    end
    ValUI.Options = 0
    ValUI.ItemOffset = 0
	ResetScriptGfxAlign()
end

---Banner
---@return nil
---@public
---@param Enabled boolean
function ValUI.Banner(Enabled, Glare)
    if type(Enabled) == "boolean" then
        if Enabled == true then


            if ValUI.CurrentMenu ~= nil then
                if ValUI.CurrentMenu() then


                    ValUI.ItemsSafeZone(ValUI.CurrentMenu)

                    if ValUI.CurrentMenu.Sprite then
                        RenderSprite(ValUI.CurrentMenu.Sprite.Dictionary, ValUI.CurrentMenu.Sprite.Texture, ValUI.CurrentMenu.X, ValUI.CurrentMenu.Y, ValUI.Settings.Items.Title.Background.Width + ValUI.CurrentMenu.WidthOffset, ValUI.Settings.Items.Title.Background.Height)
                    else
                        RenderRectangle(ValUI.CurrentMenu.X, ValUI.CurrentMenu.Y, ValUI.Settings.Items.Title.Background.Width + ValUI.CurrentMenu.WidthOffset, ValUI.Settings.Items.Title.Background.Height, ValUI.CurrentMenu.Rectangle.R, ValUI.CurrentMenu.Rectangle.G, ValUI.CurrentMenu.Rectangle.B, ValUI.CurrentMenu.Rectangle.A)
                    end

                    if Glare then

                        local ScaleformMovie = RequestScaleformMovie("MP_MENU_GLARE")
                        if not HasScaleformMovieLoaded(ScaleformMovie) then
                            ScaleformMovie = RequestScaleformMovie("MP_MENU_GLARE")
                            while not HasScaleformMovieLoaded(ScaleformMovie) do
                                Citizen.Wait(0)
                            end
                        end

                        ---@type number
                        local Glarewidth = ValUI.Settings.Items.Title.Background.Width + ValUI.CurrentMenu.WidthOffset
                        ---@type number
                        local Glareheight = ValUI.Settings.Items.Title.Background.Height
                        ---@type number
                        local GlareX = ValUI.CurrentMenu.X / 1860 + ValUI.CurrentMenu.SafeZoneSize.X / 53.211
                        ---@type number
                        local GalreY = ValUI.CurrentMenu.Y / 1080 + ValUI.CurrentMenu.SafeZoneSize.Y / 33.195020746888

                        ValUI.SetScaleformParams(ScaleformMovie, {
                            { name = "SET_DATA_SLOT", param = { GetGameplayCamRelativeHeading() } }
                        })

                        DrawScaleformMovie(ScaleformMovie, GlareX, GalreY, Glarewidth / 430, Glareheight / 100, 255, 255, 255, 255, 0)

                    end

                    RenderText(ValUI.CurrentMenu.Title, ValUI.CurrentMenu.X + ValUI.Settings.Items.Title.Text.X + (ValUI.CurrentMenu.WidthOffset / 2), ValUI.CurrentMenu.Y + ValUI.Settings.Items.Title.Text.Y, 1, ValUI.Settings.Items.Title.Text.Scale, 255, 255, 255, 255, 1)
                    ValUI.ItemOffset = ValUI.ItemOffset + ValUI.Settings.Items.Title.Background.Height
                end
            end
        end
    else
        error("Enabled is not boolean")
    end
end

---CloseAll -- TODO 
---@return nil
---@public
-- function ValUI:CloseAll()
--     ValUI.PlaySound(ValUI.Settings.Audio.Library, ValUI.Settings.Audio.Back)
--     ValUI.NextMenu = nil
--     ValUI.Visible(ValUI.CurrentMenu, false)
-- end

---Subtitle
---@return nil
---@public
function ValUI.Subtitle()
    if ValUI.CurrentMenu ~= nil then
        if ValUI.CurrentMenu() then
            ValUI.ItemsSafeZone(ValUI.CurrentMenu)
            if ValUI.CurrentMenu.Subtitle ~= "" then
                RenderRectangle(ValUI.CurrentMenu.X, ValUI.CurrentMenu.Y + ValUI.ItemOffset, ValUI.Settings.Items.Subtitle.Background.Width + ValUI.CurrentMenu.WidthOffset, ValUI.Settings.Items.Subtitle.Background.Height + ValUI.CurrentMenu.SubtitleHeight, 0, 0, 0, 255)
                RenderText(ValUI.CurrentMenu.Subtitle, ValUI.CurrentMenu.X + ValUI.Settings.Items.Subtitle.Text.X, ValUI.CurrentMenu.Y + ValUI.Settings.Items.Subtitle.Text.Y + ValUI.ItemOffset, 0, 0.26, 245, 245, 245, 255, nil, false, false, ValUI.Settings.Items.Subtitle.Background.Width + ValUI.CurrentMenu.WidthOffset)
                if ValUI.CurrentMenu.Index > ValUI.CurrentMenu.Options or ValUI.CurrentMenu.Index < 0 then
                    ValUI.CurrentMenu.Index = 1
                end
                ValUI.RefreshPagination()
                if ValUI.CurrentMenu.PageCounter == nil then
                    RenderText(ValUI.CurrentMenu.PageCounterColour .. ValUI.CurrentMenu.Index .. " / " .. ValUI.CurrentMenu.Options, ValUI.CurrentMenu.X + ValUI.Settings.Items.Subtitle.PreText.X + ValUI.CurrentMenu.WidthOffset, ValUI.CurrentMenu.Y + ValUI.Settings.Items.Subtitle.PreText.Y + ValUI.ItemOffset, 0, 0.26, 245, 245, 245, 255, 2)
                else
                    RenderText(ValUI.CurrentMenu.PageCounter, ValUI.CurrentMenu.X + ValUI.Settings.Items.Subtitle.PreText.X + ValUI.CurrentMenu.WidthOffset, ValUI.CurrentMenu.Y + ValUI.Settings.Items.Subtitle.PreText.Y + ValUI.ItemOffset, 0, 0.26, 245, 245, 245, 255, 2)
                end
                ValUI.ItemOffset = ValUI.ItemOffset + ValUI.Settings.Items.Subtitle.Background.Height
            end
        end
    end
end

---Background
---@return nil
---@public
function ValUI.Background()
    if ValUI.CurrentMenu ~= nil then
        if ValUI.CurrentMenu() then
            ValUI.ItemsSafeZone(ValUI.CurrentMenu)
            SetScriptGfxDrawOrder(0)
            RenderSprite(ValUI.Settings.Items.Background.Dictionary, ValUI.Settings.Items.Background.Texture, ValUI.CurrentMenu.X, ValUI.CurrentMenu.Y + ValUI.Settings.Items.Background.Y + ValUI.CurrentMenu.SubtitleHeight+100, ValUI.Settings.Items.Background.Width + ValUI.CurrentMenu.WidthOffset, ValUI.ItemOffset-100, 0, 0, 0, 0, 255)
            SetScriptGfxDrawOrder(1)
        end
    end
end

---Description
---@return nil
---@public
function ValUI.Description()
    if ValUI.CurrentMenu ~= nil and ValUI.CurrentMenu.Description ~= nil then
        if ValUI.CurrentMenu() then
            ValUI.ItemsSafeZone(ValUI.CurrentMenu)
            RenderRectangle(ValUI.CurrentMenu.X, ValUI.CurrentMenu.Y + ValUI.Settings.Items.Description.Bar.Y + ValUI.CurrentMenu.SubtitleHeight + ValUI.ItemOffset, ValUI.Settings.Items.Description.Bar.Width + ValUI.CurrentMenu.WidthOffset, ValUI.Settings.Items.Description.Bar.Height, 0, 0, 0, 255)
            RenderSprite(ValUI.Settings.Items.Description.Background.Dictionary, ValUI.Settings.Items.Description.Background.Texture, ValUI.CurrentMenu.X, ValUI.CurrentMenu.Y + ValUI.Settings.Items.Description.Background.Y + ValUI.CurrentMenu.SubtitleHeight + ValUI.ItemOffset, ValUI.Settings.Items.Description.Background.Width + ValUI.CurrentMenu.WidthOffset, ValUI.CurrentMenu.DescriptionHeight, 0, 0, 0, 255)
            RenderText(ValUI.CurrentMenu.Description, ValUI.CurrentMenu.X + ValUI.Settings.Items.Description.Text.X, ValUI.CurrentMenu.Y + ValUI.Settings.Items.Description.Text.Y + ValUI.CurrentMenu.SubtitleHeight + ValUI.ItemOffset, 0, 0.26, 255, 255, 255, 255, nil, false, false, ValUI.Settings.Items.Description.Background.Width + ValUI.CurrentMenu.WidthOffset)
            ValUI.ItemOffset = ValUI.ItemOffset + ValUI.CurrentMenu.DescriptionHeight + ValUI.Settings.Items.Description.Bar.Y
        end
    end
end


---Render
---@param instructionalButton boolean
---@return nil
---@public
function ValUI.Render(instructionalButton)
    if ValUI.CurrentMenu ~= nil then
        if ValUI.CurrentMenu() then
            if ValUI.CurrentMenu.Safezone then
                ResetScriptGfxAlign()
            end
            if (instructionalButton) then
                DrawScaleformMovieFullscreen(ValUI.CurrentMenu.InstructionalScaleform, 255, 255, 255, 255, 0)
            end
            ValUI.CurrentMenu.Options = ValUI.Options
            ValUI.CurrentMenu.SafeZoneSize = nil
            ValUI.Controls()
            ValUI.Options = 0
            ValUI.StatisticPanelCount = 0
            ValUI.ItemOffset = 0
            if ValUI.CurrentMenu.Controls.Back.Enabled and ValUI.CurrentMenu.Closable then
                if ValUI.CurrentMenu.Controls.Back.Pressed then
                    ValUI.CurrentMenu.Controls.Back.Pressed = false
                    local Audio = ValUI.Settings.Audio
                    ValUI.PlaySound(Audio[Audio.Use].Back.audioName, Audio[Audio.Use].Back.audioRef)
                    if ValUI.CurrentMenu.Closed ~= nil then
                        ValUI.CurrentMenu.Closed()
                    end
                    if ValUI.CurrentMenu.Parent ~= nil then
                        if ValUI.CurrentMenu.Parent() then
                            ValUI.NextMenu = ValUI.CurrentMenu.Parent
                        else
                            ValUI.NextMenu = nil
                            ValUI.Visible(ValUI.CurrentMenu, false)
                        end
                    else
                        ValUI.NextMenu = nil
                        ValUI.Visible(ValUI.CurrentMenu, false)
                    end
                end
            end
            if ValUI.NextMenu ~= nil then
                if ValUI.NextMenu() then
                    ValUI.Visible(ValUI.CurrentMenu, false)
                    ValUI.Visible(ValUI.NextMenu, true)
                    ValUI.CurrentMenu.Controls.Select.Active = false
                    ValUI.NextMenu = nil
                    ValUI.LastControl = false
                end
            end
        end
    end
end

---ItemsDescription
---@param CurrentMenu table
---@param Description string
---@param Selected boolean
---@return nil
---@public
function ValUI.ItemsDescription(CurrentMenu, Description, Selected)
    ---@type table
    if Description ~= "" or Description ~= nil then
        local SettingsDescription = ValUI.Settings.Items.Description;
        if Selected and CurrentMenu.Description ~= Description then
            CurrentMenu.Description = Description or nil
            ---@type number
            local DescriptionLineCount = GetLineCount(CurrentMenu.Description, CurrentMenu.X + SettingsDescription.Text.X, CurrentMenu.Y + SettingsDescription.Text.Y + CurrentMenu.SubtitleHeight + ValUI.ItemOffset, 0, SettingsDescription.Text.Scale, 255, 255, 255, 255, nil, false, false, SettingsDescription.Background.Width + CurrentMenu.WidthOffset)
            if DescriptionLineCount > 1 then
                CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height * DescriptionLineCount
            else
                CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height + 7
            end
        end
    end
end

---MouseBounds
---@param CurrentMenu table
---@param Selected boolean
---@param Option number
---@param SettingsButton table
---@return boolean
---@public
function ValUI.ItemsMouseBounds(CurrentMenu, Selected, Option, SettingsButton)
    ---@type boolean
    local Hovered = false
    Hovered = ValUI.IsMouseInBounds(CurrentMenu.X + CurrentMenu.SafeZoneSize.X, CurrentMenu.Y + SettingsButton.Rectangle.Y + CurrentMenu.SafeZoneSize.Y + CurrentMenu.SubtitleHeight + ValUI.ItemOffset, SettingsButton.Rectangle.Width + CurrentMenu.WidthOffset, SettingsButton.Rectangle.Height)
    if Hovered and not Selected then
        RenderRectangle(CurrentMenu.X, CurrentMenu.Y + SettingsButton.Rectangle.Y + CurrentMenu.SubtitleHeight + ValUI.ItemOffset, SettingsButton.Rectangle.Width + CurrentMenu.WidthOffset, SettingsButton.Rectangle.Height, 255, 255, 255, 20)
        if CurrentMenu.Controls.Click.Active then
            CurrentMenu.Index = Option
            local Audio = ValUI.Settings.Audio
            ValUI.PlaySound(Audio[Audio.Use].Error.audioName, Audio[Audio.Use].Error.audioRef)
        end
    end
    return Hovered;
end

---ItemsSafeZone
---@param CurrentMenu table
---@return nil
---@public
function ValUI.ItemsSafeZone(CurrentMenu)
    if not CurrentMenu.SafeZoneSize then
        CurrentMenu.SafeZoneSize = { X = 0, Y = 0 }
        if CurrentMenu.Safezone then
            CurrentMenu.SafeZoneSize = ValUI.GetSafeZoneBounds()
            SetScriptGfxAlign(76, 84)
            SetScriptGfxAlignParams(0, 0, 0, 0)
        end
    end
end

function ValUI.CurrentIsEqualTo(Current, To, Style, DefaultStyle)
    if (Current == To) then
        return Style;
    else
        return DefaultStyle or {};
    end
end

function ValUI.RefreshPagination()
    if (ValUI.CurrentMenu ~= nil) then
        if (ValUI.CurrentMenu.Index > 10) then
            local offset = ValUI.CurrentMenu.Index - 10
            ValUI.CurrentMenu.Pagination.Minimum = 1 + offset
            ValUI.CurrentMenu.Pagination.Maximum = 10 + offset
        else
            ValUI.CurrentMenu.Pagination.Minimum = 1
            ValUI.CurrentMenu.Pagination.Maximum = 10
        end
    end
end

function ValUI.IsVisible(menu, header, glare, instructional, items, panels)
    if (ValUI.Visible(menu)) then
        if (header == true) then
            ValUI.Banner(true, false)
        end
        ValUI.Subtitle()
        if (items ~= nil) then
            items()
        end
        ValUI.Background();
        ValUI.Navigation();
        ValUI.Description();
        if (panels ~= nil) then
            panels()
        end
        ValUI.Render(instructional or false)
    end
end

function ValUI.CreateWhile(wait, menu, key, closure)
    Citizen.CreateThread(function()
        while (true) do
            Citizen.Wait(wait or 0.1)

            if(key ~= nil)then
                if IsControlJustPressed(1, key) then
                    ValUI.Visible(menu, not ValUI.Visible(menu))
                end
            end

            closure()
        end
    end)
end

