ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

-----------masque 
ESX.RegisterUsableItem('Masque1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque1', source) 
end)
ESX.RegisterUsableItem('Masque1_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque1_2', source) 
end)
ESX.RegisterUsableItem('Masque1_3', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque1_3', source) 
end)





ESX.RegisterUsableItem('Masque2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque2', source) 
end)
ESX.RegisterUsableItem('Masque2_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque2_1', source) 
end)
ESX.RegisterUsableItem('Masque2_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque2_2', source) 
end)


ESX.RegisterUsableItem('Masque3', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque3', source)  
end)


ESX.RegisterUsableItem('Masque4', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque4', source) 
end)
ESX.RegisterUsableItem('Masque4_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque4_1', source) 
end)
ESX.RegisterUsableItem('Masque4_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque4_2', source) 
end)


ESX.RegisterUsableItem('Masque5', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque5', source) 
end)
ESX.RegisterUsableItem('Masque5_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque5_1', source) 
end)
ESX.RegisterUsableItem('Masque5_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque5_2', source) 
end)


ESX.RegisterUsableItem('Masque6', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque6', source) 
end)
ESX.RegisterUsableItem('Masque6_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque6_1', source) 
end)
ESX.RegisterUsableItem('Masque6_2', function(source)  
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque6_2', source) 
end)


ESX.RegisterUsableItem('Masque7', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque7', source) 
end)
ESX.RegisterUsableItem('Masque7_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque7_1', source) 
end)
ESX.RegisterUsableItem('Masque7_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque7_2', source)  
end)


ESX.RegisterUsableItem('Masque8', function(source)  
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque8', source) 
end)
ESX.RegisterUsableItem('Masque8_1', function(source)  
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque8_1', source) 
end)
ESX.RegisterUsableItem('Masque8_2', function(source)  
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque8_2', source) 
end)


ESX.RegisterUsableItem('Masque9', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque9', source) 
end)
ESX.RegisterUsableItem('Masque9_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque9_2', source) 
end)
ESX.RegisterUsableItem('Masque9_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque9_2', source) 
end) 


ESX.RegisterUsableItem('Masque10', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque10', source) 
end)
ESX.RegisterUsableItem('Masque10_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque10_1', source) 
end)
ESX.RegisterUsableItem('Masque10_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque10_2', source)  
end)


ESX.RegisterUsableItem('Masque11', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque11', source) 
end)
ESX.RegisterUsableItem('Masque11_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque11_1', source) 
end)
ESX.RegisterUsableItem('Masque11_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque11_2', source) 
end)
 

ESX.RegisterUsableItem('Masque12', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque12', source) 
end)
ESX.RegisterUsableItem('Masque12_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque12_1', source) 
end)
ESX.RegisterUsableItem('Masque12_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque12_2', source) 
end)


ESX.RegisterUsableItem('Masque13', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque13', source) 
end)
ESX.RegisterUsableItem('Masque13_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque13_1', source) 
end)
ESX.RegisterUsableItem('Masque13_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque13_2', source) 
end)


ESX.RegisterUsableItem('Masque14', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque14', source) 
end)
ESX.RegisterUsableItem('Masque14_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque14_1', source) 
end)
ESX.RegisterUsableItem('Masque14_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque14_2', source) 
end)


ESX.RegisterUsableItem('Masque15', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque15', source) 
end)
ESX.RegisterUsableItem('Masque15_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque15_1', source) 
end)
ESX.RegisterUsableItem('Masque15_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque15_2', source) 
end)


ESX.RegisterUsableItem('Masque16', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque16', source) 
end)
ESX.RegisterUsableItem('Masque16_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque16_1', source) 
end)
ESX.RegisterUsableItem('Masque16_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque16_2', source) 
end)


ESX.RegisterUsableItem('Masque17', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque17', source) 
end)
ESX.RegisterUsableItem('Masque17_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque17_1', source) 
end)
ESX.RegisterUsableItem('Masque17_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque17_2', source) 
end)


ESX.RegisterUsableItem('Masque18', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque18', source) 
end)
ESX.RegisterUsableItem('Masque18_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque18_1', source) 
end)
ESX.RegisterUsableItem('Masque18_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque18_2', source) 
end)


ESX.RegisterUsableItem('Masque19', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque19', source) 
end)
ESX.RegisterUsableItem('Masque19_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque19_1', source) 
end)
ESX.RegisterUsableItem('Masque19_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque19_2', source) 
end) 


ESX.RegisterUsableItem('Masque20', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque20', source) 
end)
ESX.RegisterUsableItem('Masque20_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque20_1', source) 
end)
ESX.RegisterUsableItem('Masque20_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque20_2', source) 
end)


ESX.RegisterUsableItem('Masque21', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque21', source) 
end)
ESX.RegisterUsableItem('Masque21_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque21_1', source) 
end)
ESX.RegisterUsableItem('Masque21_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque21_2', source) 
end)


ESX.RegisterUsableItem('Masque22', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque22', source) 
end)
ESX.RegisterUsableItem('Masque22_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque22_1', source) 
end)
ESX.RegisterUsableItem('Masque22_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque22_2', source) 
end)


ESX.RegisterUsableItem('Masque23', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque23', source) 
end)
ESX.RegisterUsableItem('Masque23_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque23_1', source) 
end)
ESX.RegisterUsableItem('Masque23_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque23_2', source) 
end)


ESX.RegisterUsableItem('Masque24', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque24', source) 
end)
ESX.RegisterUsableItem('Masque24_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque24_1', source) 
end)
ESX.RegisterUsableItem('Masque24_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque24_2', source) 
end)


ESX.RegisterUsableItem('Masque25', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque25', source) 
end)
ESX.RegisterUsableItem('Masque25_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque25_1', source) 
end)
ESX.RegisterUsableItem('Masque25_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque25_2', source) 
end)


ESX.RegisterUsableItem('Masque26', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque26', source) 
end)
ESX.RegisterUsableItem('Masque26_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque26_1', source) 
end)
ESX.RegisterUsableItem('Masque26_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque26_2', source) 
end)


ESX.RegisterUsableItem('Masque27', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque27', source) 
end)
ESX.RegisterUsableItem('Masque27_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque27_1', source) 
end)
ESX.RegisterUsableItem('Masque27_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque27_2', source) 
end)


ESX.RegisterUsableItem('Masque28', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque28', source) 
end)
ESX.RegisterUsableItem('Masque28_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque28_1', source) 
end)
ESX.RegisterUsableItem('Masque28_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque28_2', source) 
end)


ESX.RegisterUsableItem('Masque29', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque29', source) 
end)
ESX.RegisterUsableItem('Masque29_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque29_1', source) 
end)
ESX.RegisterUsableItem('Masque29_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque29_2', source) 
end)


ESX.RegisterUsableItem('Masque30', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque30', source) 
end)
ESX.RegisterUsableItem('Masque30_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque30_1', source) 
end)
ESX.RegisterUsableItem('Masque30_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)  
	TriggerClientEvent('n_vetement:Masque30_2', source) 
end) 


ESX.RegisterUsableItem('Masque31', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque31', source) 
end)
ESX.RegisterUsableItem('Masque31_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque31_1', source) 
end)
ESX.RegisterUsableItem('Masque31_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque31_2', source) 
end)


ESX.RegisterUsableItem('Masque32', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque32', source) 
end)
ESX.RegisterUsableItem('Masque32_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque32_1', source) 
end)
ESX.RegisterUsableItem('Masque32_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque32_2', source) 
end)


ESX.RegisterUsableItem('Masque33', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque33', source) 
end)
ESX.RegisterUsableItem('Masque33_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque33_1', source) 
end)
ESX.RegisterUsableItem('Masque33_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque33_2', source) 
end)


ESX.RegisterUsableItem('Masque34', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque34', source) 
end)
ESX.RegisterUsableItem('Masque34_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque34_1', source) 
end)
ESX.RegisterUsableItem('Masque34_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque34_2', source) 
end)


ESX.RegisterUsableItem('Masque35', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque35', source) 
end)
ESX.RegisterUsableItem('Masque35_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque35_1', source) 
end)
ESX.RegisterUsableItem('Masque35_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque35_2', source) 
end)


ESX.RegisterUsableItem('Masque36', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque36', source) 
end)
ESX.RegisterUsableItem('Masque36_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque36_1', source) 
end)
ESX.RegisterUsableItem('Masque36_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque36_2', source) 
end)


ESX.RegisterUsableItem('Masque37', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque37', source) 
end)
ESX.RegisterUsableItem('Masque37_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque37_1', source) 
end)
ESX.RegisterUsableItem('Masque37_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque37_2', source) 
end)


ESX.RegisterUsableItem('Masque38', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque38', source) 
end)
ESX.RegisterUsableItem('Masque38_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque38_1', source) 
end)
ESX.RegisterUsableItem('Masque38_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque38_2', source) 
end)


ESX.RegisterUsableItem('Masque39', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque39', source) 
end)
ESX.RegisterUsableItem('Masque39_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque39_1', source) 
end)
ESX.RegisterUsableItem('Masque39_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque39_2', source) 
end)


ESX.RegisterUsableItem('Masque40', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque40', source) 
end)
ESX.RegisterUsableItem('Masque40_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque40_1', source) 
end)
ESX.RegisterUsableItem('Masque40_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque40_2', source) 
end)


ESX.RegisterUsableItem('Masque41', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque41', source) 
end)
ESX.RegisterUsableItem('Masque41_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque41_1', source) 
end)
ESX.RegisterUsableItem('Masque41_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque41_2', source) 
end)


ESX.RegisterUsableItem('Masque42', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque42', source) 
end)
ESX.RegisterUsableItem('Masque42_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque42_1', source) 
end)
ESX.RegisterUsableItem('Masque42_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque42_2', source) 
end)


ESX.RegisterUsableItem('Masque43', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque43', source) 
end)
ESX.RegisterUsableItem('Masque43_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque43_1', source) 
end)
ESX.RegisterUsableItem('Masque43_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque43_2', source) 
end)


ESX.RegisterUsableItem('Masque44', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque44', source) 
end)
ESX.RegisterUsableItem('Masque44_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque44_1', source) 
end)
ESX.RegisterUsableItem('Masque44_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque44_2', source) 
end)


ESX.RegisterUsableItem('Masque45', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque45', source) 
end)
ESX.RegisterUsableItem('Masque45_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque45_1', source) 
end)
ESX.RegisterUsableItem('Masque45_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque45_2', source) 
end)


ESX.RegisterUsableItem('Masque46', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque46', source) 
end)
ESX.RegisterUsableItem('Masque46_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque46_1', source) 
end)
ESX.RegisterUsableItem('Masque46_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque46_2', source) 
end)



ESX.RegisterUsableItem('Masque47', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque47', source) 
end)
ESX.RegisterUsableItem('Masque47_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque47_1', source) 
end)
ESX.RegisterUsableItem('Masque47_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque47_2', source) 
end)


ESX.RegisterUsableItem('Masque48', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque48', source) 
end)
ESX.RegisterUsableItem('Masque48_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque48_1', source) 
end)
ESX.RegisterUsableItem('Masque48_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque48_2', source) 
end)


ESX.RegisterUsableItem('Masque49', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque49', source) 
end)
ESX.RegisterUsableItem('Masque49_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque49_1', source) 
end)
ESX.RegisterUsableItem('Masque49_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque49_2', source) 
end)


ESX.RegisterUsableItem('Masque50', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50', source) 
end)
ESX.RegisterUsableItem('Masque50_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_1', source) 
end)
ESX.RegisterUsableItem('Masque50_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_2', source) 
end)
ESX.RegisterUsableItem('Masque50_3', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_3', source) 
end)
ESX.RegisterUsableItem('Masque50_4', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_4', source) 
end)
ESX.RegisterUsableItem('Masque50_5', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_5', source) 
end)
ESX.RegisterUsableItem('Masque50_6', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_6', source) 
end)
ESX.RegisterUsableItem('Masque50_7', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_7', source) 
end)
ESX.RegisterUsableItem('Masque50_8', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_8', source) 
end)
ESX.RegisterUsableItem('Masque50_9', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque50_9', source) 
end)


ESX.RegisterUsableItem('Masque51', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51', source) 
end)
ESX.RegisterUsableItem('Masque51_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_1', source) 
end)
ESX.RegisterUsableItem('Masque51_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_2', source) 
end)
ESX.RegisterUsableItem('Masque51_3', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_3', source) 
end)
ESX.RegisterUsableItem('Masque51_4', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_4', source) 
end)
ESX.RegisterUsableItem('Masque51_5', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_5', source) 
end)
ESX.RegisterUsableItem('Masque51_6', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_6', source) 
end)
ESX.RegisterUsableItem('Masque51_7', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_7', source) 
end)
ESX.RegisterUsableItem('Masque51_8', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_8', source) 
end)
ESX.RegisterUsableItem('Masque51_9', function(source)  
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque51_9', source) 
end) 


ESX.RegisterUsableItem('Masque52', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52', source) 
end)
ESX.RegisterUsableItem('Masque52_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_1', source) 
end)
ESX.RegisterUsableItem('Masque52_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_2', source) 
end)
ESX.RegisterUsableItem('Masque52_3', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_3', source) 
end)
ESX.RegisterUsableItem('Masque52_4', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_4', source) 
end)
ESX.RegisterUsableItem('Masque52_5', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_5', source) 
end)
ESX.RegisterUsableItem('Masque52_6', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_6', source) 
end)
ESX.RegisterUsableItem('Masque52_7', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_7', source) 
end)
ESX.RegisterUsableItem('Masque52_8', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_8', source) 
end)
ESX.RegisterUsableItem('Masque52_9', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque52_9', source) 
end)



ESX.RegisterUsableItem('Masque53', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53', source) 
end)
ESX.RegisterUsableItem('Masque53_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_1', source) 
end)
ESX.RegisterUsableItem('Masque53_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_2', source) 
end)
ESX.RegisterUsableItem('Masque53_3', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_3', source) 
end)
ESX.RegisterUsableItem('Masque53_4', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_4', source) 
end)
ESX.RegisterUsableItem('Masque53_5', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_5', source) 
end)
ESX.RegisterUsableItem('Masque53_6', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_6', source) 
end)
ESX.RegisterUsableItem('Masque53_7', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_7', source) 
end)
ESX.RegisterUsableItem('Masque53_8', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_8', source) 
end)
ESX.RegisterUsableItem('Masque53_9', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque53_9', source) 
end) 


ESX.RegisterUsableItem('Masque54', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54', source) 
end)
ESX.RegisterUsableItem('Masque54_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_1', source) 
end)
ESX.RegisterUsableItem('Masque54_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_2', source) 
end)
ESX.RegisterUsableItem('Masque54_3', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_3', source) 
end)
ESX.RegisterUsableItem('Masque54_4', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_4', source) 
end)
ESX.RegisterUsableItem('Masque54_5', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_5', source) 
end)
ESX.RegisterUsableItem('Masque54_6', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_6', source) 
end)
ESX.RegisterUsableItem('Masque54_7', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_7', source) 
end)
ESX.RegisterUsableItem('Masque54_8', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_8', source) 
end)
ESX.RegisterUsableItem('Masque54_9', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque54_9', source) 
end)



ESX.RegisterUsableItem('Masque55', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque55', source) 
end)
ESX.RegisterUsableItem('Masque55_1', function(source)  
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque55_1', source) 
end)
ESX.RegisterUsableItem('Masque55_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque55_2', source) 
end)


ESX.RegisterUsableItem('Masque56', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque56', source) 
end)
ESX.RegisterUsableItem('Masque56_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque56_1', source) 
end)
ESX.RegisterUsableItem('Masque56_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque56_2', source) 
end)


ESX.RegisterUsableItem('Masque57', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque57', source) 
end)
ESX.RegisterUsableItem('Masque57_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque57_1', source) 
end)
ESX.RegisterUsableItem('Masque57_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque57_2', source) 
end) 


ESX.RegisterUsableItem('Masque58', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque58', source) 
end)
ESX.RegisterUsableItem('Masque58_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque58_1', source) 
end)
ESX.RegisterUsableItem('Masque58_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque58_2', source) 
end)


ESX.RegisterUsableItem('Masque59', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque59', source) 
end)
ESX.RegisterUsableItem('Masque59_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque59_1', source) 
end)
ESX.RegisterUsableItem('Masque59_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque59_2', source) 
end)

 
ESX.RegisterUsableItem('Masque60', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque60', source) 
end)
ESX.RegisterUsableItem('Masque60_1', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque60_1', source) 
end)
ESX.RegisterUsableItem('Masque60_2', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source) 
	TriggerClientEvent('n_vetement:Masque60_2', source) 
end)
